version: '3.7'
#https://github.com/testdrivenio/django-on-docker
services:
  web:
    build:
      context: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/static
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - .env
#    depends_on:
#      - db
  db:
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  nginx:
    build: ./nginx
    volumes:
       - static_volume:/static
    ports:
      - 1337:80
#    depends_on:
#      - web
volumes:
  static_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./static_volume
