version: '3.7'
#https://github.com/testdrivenio/django-on-docker
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static_volume:/home/app/web/staticfiles
      - ./media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  nginx:
    build: ./nginx
    volumes:
      - ./static_volume:/home/app/web/staticfiles
      - ./media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

